description: Simple Haskell project using Stack build tool
files:
- stack.yaml
- path: Setup.hs
  preprocess: true
- path: project.cabal
  output-path: $project_name.cabal
  preprocess: true
- path: ../_shared/LICENSE
  output-path: LICENSE
  preprocess: true
- path: src/Main.hs
  preprocess: true
- path: README.md
  preprocess: true
commands:
- git init
- git remote add origin $public_git_repo:$git_user_name/$project_name.git
- git config user.name "$author"
- git config user.email "$author_email"
- git add .
