#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

script_dir=$(cd $(dirname $0); pwd -P)
repo_dir=$(dirname $script_dir)

source $repo_dir/.env
cd $repo_dir/backend
stack setup
stack build --fast
stack exec {{project_name}}-codegen -- $repo_dir/frontend/src/{{module_name}}/Codegen.elm {{module_name}}.Codegen
